accounts/urls.py
from django.urls import path, re_path

from accounts.views import register, index, update_user, update_password
from catalog.views import product_list, category, product

app_name = 'accounts'
urlpatterns = [
    path('', index, name='index'),
    path('registro/', register, name='register'),
    path('alterar-senha/', update_password, name='update_password'),
    path('alterar-dados/', update_user, name='update_user'),
]

catalog/urls.py
from django.urls import path
from catalog.views import product_list, category, product

app_name = 'catalog'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:slug>/', category, name='category'),
    path('produtos/<slug:slug>', product, name='product'),
]

checkout/urls.py
from django.urls import path
from checkout.views import create_cartitem, cart_item


app_name = 'checkout'
urlpatterns = [
    path('carrinho/adicionar/<slug:slug>', create_cartitem, name='create_cartitem'),
    path('carrinho/', cart_item, name='cart_item')
]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static
from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contato/', contact, name='contact'),
    path('entrar/', LoginView.as_view(template_name='login.html'), name='login'),
    path('sair/', LogoutView.as_view(next_page='index'), name='logout'),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('compras/', include('checkout.urls', namespace='checkout')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail


class ContactForm(forms.Form):
    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message_body = f"Nome: {name}\nE-mail: {email}\n{message}"
        subject = "CK Estofados"
        sender = settings.DEFAULT_FROM_EMAIL
        recipient = settings.DEFAULT_FROM_EMAIL
        send_mail(subject, message_body, sender, [recipient])

core/views.py
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, CreateView
from django.contrib.auth import get_user_model
from .forms import ContactForm
from django.contrib import messages

# def index(request):
#     return render(request, 'index.html')

# class IndexView(View):
#     def get(self, request):
#         return render(request, 'index.html')

User = get_user_model()


class IndexView(TemplateView):
    template_name = 'index.html'

index = IndexView.as_view()

def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
        # messages.success(request, 'Mensagem enviada com sucesso!')
    elif request.method == 'POST':
        messages.error(request, 'Formulário inválido')
    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title>{% block title %}CK Estofados{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen"/>
  <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen"/>
  <link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen"/>
</head>
<body>
{% comment %}
<div class="navbar navbar-default navbar-fixed-top" style="background: #4347a4">
{% endcomment %}
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="{% url 'index' %}" class="navbar-brand">CK Estofados</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'index' %}">Início</a>
        </li>
        <li>
          <a href="{% url 'catalog:product_list' %}">Produtos</a>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}"
             id="download">Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu" aria-labelledby="download">
            {% for category in categories %}
              <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li>
          <a href="{% url 'contact' %}">Contato</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Sair</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Entrar</a></li>
          <li><a href="{% url 'accounts:register' %}">Registro</a></li>
        {% endif %}
        <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container margin-top">
  {% block messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message   }}
      </div>
    {% endfor %}
  {% endblock %}
  {% block container %}{% endblock %}
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-unstyled">
          <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
          <li><a href="">Início</a></li>
          <li><a href="">Produtos</a></li>
          <li><a href="">Contato</a></li>
          <li><a href="">Termos e Privacidade</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  Contato | {{ block.super }}
{% endblock %}

{% block container %}
  <div class="page-header">
    {% if success %}
    <div class="alert alert-success">
    Mensagem enviada com sucesso!
    </div>
    {% endif %}
    <h1>Fale conosco</h1>
    <form class="form-horizontal" action="" method="post">
    {% csrf_token %}
      <fieldset>
        {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
          <div class="col-md-9">
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Enviar</button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block container %}
  <div class="jumbotron page-header">
    <img src="{% static 'images/logo-ck.jpg' %}" alt="Logo CK" width="100" height="100">
    <h1>CK Estofados - Loja de Fábrica</h1>
    <h2>Móveis</h2>
    <p>Não cobramos taxa de entrega para toda Baixada Santista</p>
    <p><a class="btn btn-primary">Saiba mais</a></p>
  </div>
{% endblock %}
{% static 'assets/custom.min.css' %}"

core/templates/login.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="page-header">
        <h1>Entrar</h1>
      </div>
      <form class="form-horizontal" method="post">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
          {{ error }}
          </div>
        {% endfor %}
        <fieldset>
          <div class="form-group{% if form.username.errors %}has-error{% endif %}">
            <label for="{{ form.username.auto_id }}"
                   class="col-md-3 control-label">{{ form.username.label }}</label>
            <div class="col-md-9">
              {% render_field form.username class="form-control" %}
              {% for error in form.username.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="form-group{% if form.password.errors %}has-error{% endif %}">
            <label for="{{ form.password.auto_id }}"
                   class="col-md-3 control-label">{{ form.password.label }}</label>
            <div class="col-md-9">
              {% render_field form.password class="form-control" %}
              {% for error in form.password.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="form-group">
            <div class="col-md-9 col-md-offset-3">
              <button type="submit" class="btn btn-primary">Enviar
              </button>
            </div>
          </div>
        </fieldset>
      </form>
    </div>
  </div>
{% endblock %}

core/templates/pagination.html
  <div class="row">
    <div class="col-md-12">
      <nav>
        <ul class="pagination">
          {% for page in paginator.page_range %}
            <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}">{{ page }}</a></li>
          {% endfor %}
        </ul>
      </nav>
    </div>
  </div>